/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "ap-southeast-2",
    "aws_cognito_identity_pool_id": "ap-southeast-2:0886736d-8703-4a37-b5a1-c4047a57092b",
    "aws_cognito_region": "ap-southeast-2",
    "aws_user_pools_id": "ap-southeast-2_XOuBzq5Aq",
    "aws_user_pools_web_client_id": "69bk3fvg35j5u7j1gsbl00ev13",
    "oauth": {},
    "aws_appsync_graphqlEndpoint": "https://t4q3npv46jahfmfsfuvcad5ve4.appsync-api.ap-southeast-2.amazonaws.com/graphql",
    "aws_appsync_region": "ap-southeast-2",
    "aws_appsync_authenticationType": "API_KEY",
    "aws_appsync_apiKey": "da2-m63kli4vzjainlxlord22jjvea"
};


export default awsmobile;
